### ISSUE TITLE
Notifications not working

### ISSUE THREAD

**Issue by gabeluci** [eduardoboucas/staticman#253]
I'm having trouble getting notifications working for [my website](https://gabescode.com) running on GitHub Pages.

I created my own staticman instance (https://comments.gabescode.com) due to the current trouble with the public API. If there is a way to see logs, I would love to know. But I have tested while running "npm start" from the console to see the output, but there isn't a whole lot.

You can see my [staticman.yml here](https://github.com/gabeluci/gabeluci.github.io/blob/master/staticman.yml).

For the Mailgun domain, I assume that's just the domain I registered with them. In my case, that's mg.gabescode.com (although I don't understand why that needs to be encrypted? seems pretty public)

For the Mailgun API key, I have tried encrypting the API key with and without the "key-" prefix. With the "key-" prefix, I see this on the console:

```
(node:31697) UnhandledPromiseRejectionWarning: Error: Unauthorized
    at IncomingMessage.<anonymous> (/var/www/staticman/node_modules/mailgun-js/lib/request.js:309:15)
    at IncomingMessage.emit (events.js:193:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
(node:31697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If I omit the "key-" prefix, I don't see any errors on the console. But I also see nothing in my Mailgun logs or any mailing lists created.

Any ideas?

I think unrelated, but I do see this happening regardless of the Mailgun API key I use:

    Warning: configuration param 'allowedOrigins' not declared in the schema

**Comment by gabeluci** [comment]
Argh. Ok. I figured it out. I was missing the `options[subscribe]` field in the form. Once I added it, everything started working.

    <input type="hidden" name="options[subscribe]" value="email">

But I did need the Mailgun key without the "key-" prefix.
