### ISSUE TITLE
Error: error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by Skyost** [eduardoboucas/staticman#341]
Hello,

I was setting up my own Staticman instance thanks to the instructions given [here](https://github.com/eduardoboucas/staticman/issues/332#issuecomment-594310595) but I'm getting the following error :

```
2020-03-15T17:43:42.739406+00:00 app[web.1]: (node:24) UnhandledPromiseRejectionWarning: Error: error:0909006C:PEM routines:get_name:no start line
2020-03-15T17:43:42.739448+00:00 app[web.1]:     at Sign.sign (internal/crypto/sig.js:112:29)
2020-03-15T17:43:42.739449+00:00 app[web.1]:     at Object.sign (/app/node_modules/jwa/index.js:152:45)
2020-03-15T17:43:42.739450+00:00 app[web.1]:     at Object.jwsSign [as sign] (/app/node_modules/jws/lib/sign-stream.js:32:24)
2020-03-15T17:43:42.739450+00:00 app[web.1]:     at Object.module.exports [as sign] (/app/node_modules/jsonwebtoken/sign.js:204:16)
2020-03-15T17:43:42.739451+00:00 app[web.1]:     at getSignedJsonWebToken (/app/node_modules/@octokit/app/dist-node/index.js:31:30)
2020-03-15T17:43:42.739451+00:00 app[web.1]:     at GitHub._authenticate (/app/lib/GitHub.js:58:21)
2020-03-15T17:43:42.739452+00:00 app[web.1]:     at /app/lib/GitHub.js:31:32
2020-03-15T17:43:42.739453+00:00 app[web.1]:     at new GitHub (/app/lib/GitHub.js:46:7)
2020-03-15T17:43:42.739454+00:00 app[web.1]:     at Object.module.exports.create (/app/lib/GitServiceFactory.js:11:14)
2020-03-15T17:43:42.739454+00:00 app[web.1]:     at /app/lib/Staticman.js:32:35
2020-03-15T17:43:42.739454+00:00 app[web.1]:     at new Staticman (/app/lib/Staticman.js:46:7)
2020-03-15T17:43:42.739455+00:00 app[web.1]:     at module.exports (/app/controllers/process.js:126:27)
2020-03-15T17:43:42.739455+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-03-15T17:43:42.739456+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2020-03-15T17:43:42.739456+00:00 app[web.1]:     at /app/server.js:169:14
2020-03-15T17:43:42.739456+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-03-15T17:43:42.739457+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2020-03-15T17:43:42.739457+00:00 app[web.1]:     at /app/server.js:144:14
2020-03-15T17:43:42.739457+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-03-15T17:43:42.739457+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2020-03-15T17:43:42.739458+00:00 app[web.1]:     at /app/server.js:129:14
2020-03-15T17:43:42.739458+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-03-15T17:43:42.739499+00:00 app[web.1]: (node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
2020-03-15T17:43:42.739592+00:00 app[web.1]: (node:24) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-03-15T17:44:01.677846+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-03-15T17:44:01.771568+00:00 heroku[web.1]: Process exited with status 143
2020-03-15T17:44:01.696691+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST 
path="/v3/entry/github/Skyost/Bacomathiques/master/comments" host=skyost-staticman.herokuapp.com request_id=58374025-eb41-4ec4-81c3-5e139ae2ff05 fwd="91.160.105.117" dyno=web.1 connect=0ms service=18989ms status=503 bytes=0 protocol=https
```

**Comment by Skyost** [comment]
Okay, seems the private key must be entered without line breaks. But I'm now encountering a http 500 error on the client side. Nothing particular on the server side.
