### ISSUE TITLE
code: 'ERR_OSSL_UNSUPPORTED'

### ISSUE THREAD

**Issue by metapodcod** [eduardoboucas/staticman#435]
```
2021-11-21T12:02:25.867998+00:00 heroku[web.1]: Process exited with status 1
2021-11-21T12:02:25.955421+00:00 heroku[web.1]: State changed from up to crashed
2021-11-21T12:02:25.721554+00:00 app[web.1]: node:internal/crypto/sig:131
2021-11-21T12:02:25.721561+00:00 app[web.1]:   const ret = this[kHandle].sign(data, format, type, passphrase, rsaPadding,
2021-11-21T12:02:25.721562+00:00 app[web.1]:                             ^
2021-11-21T12:02:25.721562+00:00 app[web.1]: 
2021-11-21T12:02:25.721564+00:00 app[web.1]: Error: error:1E08010C:DECODER routines::unsupported
2021-11-21T12:02:25.721564+00:00 app[web.1]:     at Sign.sign (node:internal/crypto/sig:131:29)
2021-11-21T12:02:25.721564+00:00 app[web.1]:     at Object.sign (/app/node_modules/jwa/index.js:152:45)
2021-11-21T12:02:25.721565+00:00 app[web.1]:     at Object.jwsSign [as sign] (/app/node_modules/jws/lib/sign-stream.js:32:24)
2021-11-21T12:02:25.721566+00:00 app[web.1]:     at Object.module.exports [as sign] (/app/node_modules/jsonwebtoken/sign.js:204:16)
2021-11-21T12:02:25.721566+00:00 app[web.1]:     at getSignedJsonWebToken (/app/node_modules/@octokit/app/dist-node/index.js:31:30)
2021-11-21T12:02:25.721566+00:00 app[web.1]:     at GitHub._authenticate (/app/lib/GitHub.js:58:21)
2021-11-21T12:02:25.721567+00:00 app[web.1]:     at /app/lib/GitHub.js:31:32
2021-11-21T12:02:25.721568+00:00 app[web.1]:     at new GitHub (/app/lib/GitHub.js:46:7)
2021-11-21T12:02:25.721568+00:00 app[web.1]:     at Object.module.exports.create (/app/lib/GitServiceFactory.js:11:14)
2021-11-21T12:02:25.721569+00:00 app[web.1]:     at /app/lib/Staticman.js:32:35
2021-11-21T12:02:25.721569+00:00 app[web.1]:     at new Staticman (/app/lib/Staticman.js:46:7)
2021-11-21T12:02:25.721569+00:00 app[web.1]:     at module.exports (/app/controllers/process.js:126:27)
2021-11-21T12:02:25.721570+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2021-11-21T12:02:25.721570+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2021-11-21T12:02:25.721570+00:00 app[web.1]:     at /app/server.js:169:14
2021-11-21T12:02:25.721571+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2021-11-21T12:02:25.721571+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2021-11-21T12:02:25.721571+00:00 app[web.1]:     at /app/server.js:144:14
2021-11-21T12:02:25.721572+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2021-11-21T12:02:25.721572+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2021-11-21T12:02:25.721572+00:00 app[web.1]:     at /app/server.js:129:14
2021-11-21T12:02:25.721573+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) {
2021-11-21T12:02:25.721573+00:00 app[web.1]:   library: 'DECODER routines',
2021-11-21T12:02:25.721573+00:00 app[web.1]:   reason: 'unsupported',
2021-11-21T12:02:25.721574+00:00 app[web.1]:   code: 'ERR_OSSL_UNSUPPORTED'
2021-11-21T12:02:25.721574+00:00 app[web.1]: }
2021-11-21T12:02:25.721577+00:00 app[web.1]: 
2021-11-21T12:02:25.721578+00:00 app[web.1]: Node.js v17.1.0
2021-11-21T12:02:25.730844+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/v3/entry/github/myblog/blog/master/comments" host=my.herokuapp.com request_id=myreqid fwd="myip" dyno=web.1 connect=0ms service=19ms status=503 bytes=0 protocol=https
```

**Comment by Siphonophora** [comment]
I just set up staticman on heroku and got the same error.

**Comment by Siphonophora** [comment]
@metapodcod Figured it out for me. I had the wrong private key for github. Specifically, when I asked github to create the private key for my app, i used the string it showed on the website, instead of the contents of the .pem file it downloaded.

**Comment by Ashimelis** [comment]
when I try to solve or install npx create-react-app it shows me an error like "code ERR-OSSL_UNSUPPORTED" so how could I solve it
