### ISSUE TITLE
 Error: Require an `oauthToken` or `token` option                                 

### ISSUE THREAD

**Issue by scbot1729** [eduardoboucas/staticman#438]
Here is the stack trace, what is wrong?

>at /root/staticman/lib/GitHub.js:33:15                            [20/1834]
    at new GitHub (/root/staticman/lib/GitHub.js:46:7)                         
    at Object.module.exports.create (/root/staticman/lib/GitServiceFactory.js:11:14)                                                                          
    at /root/staticman/lib/Staticman.js:32:35                                      at new Staticman >>>...(/root/staticman/lib/Staticman.js:46:7)                   
    at module.exports (/root/staticman/controllers/process.js:126:27)              at Layer.handle [as handle_request] (/root/staticman/node_modules/express/l
ib/router/layer.js:95:5)                                                           at next (/root/staticman/node_modules/express/lib/router/route.js:137:13)  
    at /root/staticman/server.js:169:14                                            at Layer.handle [as handle_request] (/root/staticman/node_modules/express/l
ib/router/layer.js:95:5)                                                           at next >(/root/staticman/node_modules/express/lib/router/route.js:137:13)      at /root/staticman/server.js:144:14                                            at Layer.handle [as handle_request] >>>(/root/staticman/node_modules/express/lib/router/layer.js:95:5)                                                           >at next (/root/staticman/node_modules/express/lib/router/route.js:137:13)  
    at /root/staticman/server.js:129:14                                            at Layer.handle [as handle_request] >(/root/staticman/node_modules/express/lib/router/layer.js:95:5)

*Here is the config*
 `config.production.json`
```
{ "githubToken": "XXX",
  "githubPrivateKey": " -----BEGIN RSA PRIVATE KEY----- xXX",
   "rsaPrivateKey": " -----BEGIN RSA PRIVATE KEY----- XXX",
   "port": 8080
}
```

And the staticman.yml is
same as **staticman.sample.yml**

What am I doing wrong? I posted to 

`http://spamcheetah.com:8080/v3/entry/github/<bot>/<repo>/master/comments`

**Comment by JaderDias** [comment]
If you're using the legacy config githubToken, you need to have options version = 1 or 2
https://github.com/eduardoboucas/staticman/blob/master/lib/GitHub.js#L21
